#!/usr/bin/env bash
# ssh-config.sh — SSH configuration TUI (macOS only)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_CONFIG_FILE="$SCRIPT_DIR/ssh_config"
DRY_RUN=false

# ── macOS guard ───────────────────────────────────────────────────────────────
if [ "$(uname -s)" != "Darwin" ]; then
  echo "  ssh-config.sh: skipped (macOS only)"
  exit 0
fi

# ── Platform ──────────────────────────────────────────────────────────────────
# shellcheck source=platform.sh
source "$SCRIPT_DIR/platform.sh"

# ── Colors ────────────────────────────────────────────────────────────────────
BOLD='\033[1m'
DIM='\033[2m'
PURPLE='\033[38;2;105;48;122m'
LAVENDER='\033[38;2;239;220;249m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

info()    { echo -e "  ${LAVENDER}${1}${RESET}"; }
success() { echo -e "  ${GREEN}✓${RESET}  ${1}"; }
warn()    { echo -e "  ${YELLOW}!${RESET}  ${1}"; }
error()   { echo -e "  ${RED}✗${RESET}  ${1}" >&2; }
header()  { echo -e "\n${BOLD}${PURPLE}${1}${RESET}"; }

# ── run_cmd ───────────────────────────────────────────────────────────────────
run_cmd() {
  if [ "$DRY_RUN" = "true" ]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

# ── generate_ssh_config ───────────────────────────────────────────────────────
# Builds full ssh_config content as a string from globals:
#   AUTH_METHOD        — "1password" | "file" | "fallback"
#   ENABLED[]          — array of enabled feature keys
#   DISABLED[]         — array of disabled feature keys
#   VARIANTS[]         — associative array: keepalive=<N|"no">, control_persist=<N|"yes">
#   KEYGEN_PATH        — (optional) path to key file for IdentityFile
generate_ssh_config() {
  local ts; ts="$(date '+%Y-%m-%d %H:%M:%S')"
  local out=""

  out+="# ~/.ssh/config — generated by ssh-config.sh"$'\n'
  out+="# Generated: ${ts}"$'\n'
  out+="# Auth method: ${AUTH_METHOD}"$'\n'
  out+="# Re-run ./ssh-config.sh to regenerate."$'\n'
  out+=""$'\n'
  out+="Host *"$'\n'

  # ── Auth ──────────────────────────────────────────────────────────────────
  out+="    # ── Auth ──────────────────────────────────────────────────────────────────"$'\n'
  out+="    AddKeysToAgent yes"$'\n'
  if [ "${DOTFILES_OS:-}" = "macos" ]; then
    out+="    UseKeychain yes"$'\n'
  fi

  case "$AUTH_METHOD" in
    1password)
      out+="    IdentityAgent \"~/.1password/agent.sock\""$'\n'
      ;;
    file)
      local key_path="${KEYGEN_PATH:-~/.ssh/id_ed25519}"
      out+="    IdentityFile ${key_path}"$'\n'
      ;;
    fallback)
      local key_path="${KEYGEN_PATH:-~/.ssh/id_ed25519}"
      out+="    IdentityAgent \"~/.1password/agent.sock\""$'\n'
      out+="    IdentityFile ${key_path}"$'\n'
      ;;
  esac

  # ── Keepalive ─────────────────────────────────────────────────────────────
  local keepalive="${VARIANTS[keepalive]:-60}"
  if [ "$keepalive" != "no" ]; then
    out+=""$'\n'
    out+="    # ── Keepalive ─────────────────────────────────────────────────────────────"$'\n'
    out+="    ServerAliveInterval ${keepalive}"$'\n'
    out+="    ServerAliveCountMax 3"$'\n'
  fi

  # ── Multiplexing ──────────────────────────────────────────────────────────
  local mux_on=false
  for f in "${ENABLED[@]+"${ENABLED[@]}"}"; do
    [ "$f" = "multiplexing" ] && mux_on=true && break
  done

  if [ "$mux_on" = "true" ]; then
    local cp="${VARIANTS[control_persist]:-600}"
    out+=""$'\n'
    out+="    # ── Multiplexing ──────────────────────────────────────────────────────────"$'\n'
    out+="    ControlMaster auto"$'\n'
    out+="    ControlPath ~/.ssh/sockets/%r@%h-%p"$'\n'
    out+="    ControlPersist ${cp}"$'\n'
  fi

  # ── Security ──────────────────────────────────────────────────────────────
  local hash_on=false
  for f in "${ENABLED[@]+"${ENABLED[@]}"}"; do
    [ "$f" = "hash_known_hosts" ] && hash_on=true && break
  done

  if [ "$hash_on" = "true" ]; then
    out+=""$'\n'
    out+="    # ── Security ──────────────────────────────────────────────────────────────"$'\n'
    out+="    HashKnownHosts yes"$'\n'
  fi

  printf '%s' "$out"
}

# ── Source-only guard (for testing) ──────────────────────────────────────────
# Set SSH_CONFIG_SOURCE_ONLY=1 to source this file without running install logic.
if [ "${SSH_CONFIG_SOURCE_ONLY:-}" = "1" ]; then
  return 0 2>/dev/null || exit 0
fi

# ── Arg parsing ───────────────────────────────────────────────────────────────
case "${1:-}" in
  --dry-run) DRY_RUN=true ;;
  --status)  : ;;
  "")        : ;;
  *) error "Unknown flag: ${1}"; echo "Usage: ./ssh-config.sh [--status|--dry-run]" >&2; exit 1 ;;
esac

echo "ssh-config.sh: not yet implemented"
