#!/usr/bin/env bash
# ssh-config.sh — SSH configuration TUI (macOS only)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_CONFIG_FILE="$SCRIPT_DIR/ssh_config"
DRY_RUN=false

# ── macOS guard ───────────────────────────────────────────────────────────────
if [ "$(uname -s)" != "Darwin" ]; then
  echo "  ssh-config.sh: skipped (macOS only)"
  exit 0
fi

# ── Platform ──────────────────────────────────────────────────────────────────
# shellcheck source=platform.sh
source "$SCRIPT_DIR/platform.sh"

# ── Colors ────────────────────────────────────────────────────────────────────
BOLD='\033[1m'
DIM='\033[2m'
PURPLE='\033[38;2;105;48;122m'
LAVENDER='\033[38;2;239;220;249m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

info()    { echo -e "  ${LAVENDER}${1}${RESET}"; }
success() { echo -e "  ${GREEN}✓${RESET}  ${1}"; }
warn()    { echo -e "  ${YELLOW}!${RESET}  ${1}"; }
error()   { echo -e "  ${RED}✗${RESET}  ${1}" >&2; }
header()  { echo -e "\n${BOLD}${PURPLE}${1}${RESET}"; }

# ── run_cmd ───────────────────────────────────────────────────────────────────
run_cmd() {
  if [ "$DRY_RUN" = "true" ]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

# ── generate_ssh_config ───────────────────────────────────────────────────────
# Builds full ssh_config content as a string from globals:
#   AUTH_METHOD        — "1password" | "file" | "fallback"
#   ENABLED[]          — array of enabled feature keys
#   DISABLED[]         — array of disabled feature keys
#   VARIANTS[]         — associative array: keepalive=<N|"no">, control_persist=<N|"yes">
#   KEYGEN_PATH        — (optional) path to key file for IdentityFile
generate_ssh_config() {
  local ts; ts="$(date '+%Y-%m-%d %H:%M:%S')"
  local out=""

  out+="# ~/.ssh/config — generated by ssh-config.sh"$'\n'
  out+="# Generated: ${ts}"$'\n'
  out+="# Auth method: ${AUTH_METHOD}"$'\n'
  out+="# Re-run ./ssh-config.sh to regenerate."$'\n'
  out+=""$'\n'
  out+="Host *"$'\n'

  # ── Auth ──────────────────────────────────────────────────────────────────
  out+="    # ── Auth ──────────────────────────────────────────────────────────────────"$'\n'
  out+="    AddKeysToAgent yes"$'\n'
  if [ "${DOTFILES_OS:-}" = "macos" ]; then
    out+="    UseKeychain yes"$'\n'
  fi

  case "$AUTH_METHOD" in
    1password)
      out+="    IdentityAgent \"~/.1password/agent.sock\""$'\n'
      ;;
    file)
      local key_path="${KEYGEN_PATH:-~/.ssh/id_ed25519}"
      out+="    IdentityFile ${key_path}"$'\n'
      ;;
    fallback)
      local key_path="${KEYGEN_PATH:-~/.ssh/id_ed25519}"
      out+="    IdentityAgent \"~/.1password/agent.sock\""$'\n'
      out+="    IdentityFile ${key_path}"$'\n'
      ;;
  esac

  # ── Keepalive ─────────────────────────────────────────────────────────────
  local keepalive="${VARIANTS[keepalive]:-60}"
  if [ "$keepalive" != "no" ]; then
    out+=""$'\n'
    out+="    # ── Keepalive ─────────────────────────────────────────────────────────────"$'\n'
    out+="    ServerAliveInterval ${keepalive}"$'\n'
    out+="    ServerAliveCountMax 3"$'\n'
  fi

  # ── Multiplexing ──────────────────────────────────────────────────────────
  local mux_on=false
  for f in "${ENABLED[@]+"${ENABLED[@]}"}"; do
    [ "$f" = "multiplexing" ] && mux_on=true && break
  done

  if [ "$mux_on" = "true" ]; then
    local cp="${VARIANTS[control_persist]:-600}"
    out+=""$'\n'
    out+="    # ── Multiplexing ──────────────────────────────────────────────────────────"$'\n'
    out+="    ControlMaster auto"$'\n'
    out+="    ControlPath ~/.ssh/sockets/%r@%h-%p"$'\n'
    out+="    ControlPersist ${cp}"$'\n'
  fi

  # ── Security ──────────────────────────────────────────────────────────────
  local hash_on=false
  for f in "${ENABLED[@]+"${ENABLED[@]}"}"; do
    [ "$f" = "hash_known_hosts" ] && hash_on=true && break
  done

  if [ "$hash_on" = "true" ]; then
    out+=""$'\n'
    out+="    # ── Security ──────────────────────────────────────────────────────────────"$'\n'
    out+="    HashKnownHosts yes"$'\n'
  fi

  printf '%s' "$out"
}

# ── Source-only guard (for testing) ──────────────────────────────────────────
# Set SSH_CONFIG_SOURCE_ONLY=1 to source this file without running install logic.
if [ "${SSH_CONFIG_SOURCE_ONLY:-}" = "1" ]; then
  return 0 2>/dev/null || exit 0
fi

# ── cmd_status ────────────────────────────────────────────────────────────────
cmd_status() {
  header "SSH Configuration Status"
  echo ""

  # 1. Symlink check
  if [ -L "$HOME/.ssh/config" ] && [ "$(readlink "$HOME/.ssh/config")" = "$SSH_CONFIG_FILE" ]; then
    success "~/.ssh/config → ${SSH_CONFIG_FILE}"
  else
    warn "~/.ssh/config is not symlinked to ${SSH_CONFIG_FILE}"
  fi

  # 2. Permissions
  local perms; perms="$(stat -f '%OLp' "$HOME/.ssh" 2>/dev/null || echo "?")"
  if [ "$perms" = "700" ]; then
    success "~/.ssh permissions: 700"
  else
    warn "~/.ssh permissions: ${perms} (expected 700)"
  fi

  # 3. Sockets dir
  if [ -d "$HOME/.ssh/sockets" ]; then
    success "~/.ssh/sockets/ exists"
  else
    warn "~/.ssh/sockets/ missing — multiplexing will fail"
  fi

  # 4. 1Password agent socket
  if [ -S "$HOME/.1password/agent.sock" ]; then
    success "1Password agent socket: ~/.1password/agent.sock"
  else
    warn "1Password agent socket not found (app may be closed)"
  fi

  # 5. Key files
  local keys=()
  while IFS= read -r -d '' key; do
    keys+=("$key")
  done < <(find "$HOME/.ssh" -maxdepth 1 -name 'id_*' ! -name '*.pub' -print0 2>/dev/null)

  if [ "${#keys[@]}" -eq 0 ]; then
    warn "No SSH key files found (id_*)"
  else
    for key in "${keys[@]}"; do
      local fp; fp="$(ssh-keygen -l -f "$key" 2>/dev/null | awk '{print $2, $4}' || echo "unreadable")"
      success "Key: ${key} — ${fp}"
    done
  fi

  # 6. Auth method from generated config
  local method="unknown"
  if [ -f "$SSH_CONFIG_FILE" ]; then
    method="$(grep '^# Auth method:' "$SSH_CONFIG_FILE" 2>/dev/null | head -1 | sed 's/# Auth method: //' || echo "unknown")"
  fi
  info "Auth method: ${method}"

  echo ""
}

# ── main (TUI stages — stub, filled in later tasks) ───────────────────────────
stage_keygen() {
  KEYGEN_PATH=""
  KEYGEN_TYPE="ed25519"
  KEYGEN_COMMENT=""
  KEYGEN_PASSPHRASE="no"

  # Skip entirely if auth is 1password-only — no key files needed
  if [ "$AUTH_METHOD" = "1password" ]; then
    return
  fi

  header "Stage 3 — Key generation"
  echo ""

  # Key name
  local key_name="id_ed25519"
  info "Key file name (in ~/.ssh/):"
  read -r -p "  Name [${key_name}]: " input_name
  [ -n "$input_name" ] && key_name="$input_name"
  KEYGEN_PATH="$HOME/.ssh/${key_name}"

  # Key already exists — skip generation
  if [ -f "$KEYGEN_PATH" ]; then
    local fp; fp="$(ssh-keygen -l -f "$KEYGEN_PATH" 2>/dev/null | awk '{print $2, $4}' || echo "unreadable")"
    success "Key already exists at ${KEYGEN_PATH} — ${fp}"
    return
  fi

  # Key type
  echo ""
  info "Key type:"
  local PS3="  Choose: "
  select kt in "ed25519 (recommended)" "rsa" "ecdsa"; do
    case "$REPLY" in
      1) KEYGEN_TYPE="ed25519"; break ;;
      2) KEYGEN_TYPE="rsa";     break ;;
      3) KEYGEN_TYPE="ecdsa";   break ;;
      *) warn "Enter 1, 2, or 3" ;;
    esac
  done

  # Comment
  echo ""
  info "Key comment (email or label — leave empty for none):"
  read -r -p "  Comment: " KEYGEN_COMMENT

  # Passphrase
  echo ""
  info "Passphrase:"
  select pp in "Set a passphrase (prompted during generation)" "No passphrase (empty)"; do
    case "$REPLY" in
      1) KEYGEN_PASSPHRASE="yes"; break ;;
      2) KEYGEN_PASSPHRASE="no";  break ;;
      *) warn "Enter 1 or 2" ;;
    esac
  done
}
stage_write()  { info "Write stage not yet implemented"; }

main() {
  # ── Non-interactive guard ─────────────────────────────────────────────────
  if [ ! -t 0 ] && [ "$DRY_RUN" = "false" ]; then
    info "No TTY detected — skipping interactive TUI"
    exit 0
  fi

  # ── Non-interactive dry-run: skip TUI, use defaults, show output ──────────
  # --dry-run bypasses the TTY guard above but select menus need a terminal.
  # When stdin is not a TTY and DRY_RUN=true, set defaults and skip to write.
  if [ ! -t 0 ] && [ "$DRY_RUN" = "true" ]; then
    AUTH_METHOD="fallback"
    ENABLED=(multiplexing hash_known_hosts)
    DISABLED=()
    declare -A VARIANTS=([keepalive]="60" [control_persist]="600")
    KEYGEN_PATH=""
    stage_write
    return
  fi

  header "SSH Configuration"

  # ── Stage 1 — Auth method ─────────────────────────────────────────────────
  header "Stage 1 — Auth method"
  echo ""
  info "How should SSH authenticate?"
  echo ""

  local PS3="  Choose auth method: "
  select choice in \
    "1Password agent only" \
    "File-based keys only" \
    "1Password with file-based fallback (recommended)"; do
    case "$REPLY" in
      1) AUTH_METHOD="1password"; break ;;
      2) AUTH_METHOD="file";      break ;;
      3) AUTH_METHOD="fallback";  break ;;
      *) warn "Invalid choice — enter 1, 2, or 3" ;;
    esac
  done

  success "Auth method: ${AUTH_METHOD}"

  # ── Stage 2 — Connection settings ─────────────────────────────────────────
  header "Stage 2 — Connection settings"
  echo ""

  ENABLED=()
  DISABLED=()
  declare -A VARIANTS=()

  # Feature toggles: fzf multi-select or fallback to all-on preset
  if command -v fzf >/dev/null 2>&1; then
    info "Use Space to toggle, Enter to confirm"
    echo ""
    local selected
    selected="$(printf '%s\n' "multiplexing" "hash_known_hosts" | \
      fzf --multi \
          --prompt="  Enable features > " \
          --header="Connection features (Space=toggle, Enter=confirm)" \
          --bind=space:toggle \
          --no-sort \
          --marker='*'
    )" || selected=""

    while IFS= read -r feat; do
      [ -n "$feat" ] && ENABLED+=("$feat")
    done <<< "$selected"

    for feat in multiplexing hash_known_hosts; do
      local found=false
      for e in "${ENABLED[@]+"${ENABLED[@]}"}"; do [ "$e" = "$feat" ] && found=true && break; done
      [ "$found" = "false" ] && DISABLED+=("$feat")
    done
  else
    ENABLED=(multiplexing hash_known_hosts)
    info "fzf not found — enabling all connection features"
  fi

  # Keepalive variant
  echo ""
  info "Keepalive interval (ServerAliveInterval):"
  local PS3="  Choose: "
  select ka in "60s (default)" "30s" "disabled"; do
    case "$REPLY" in
      1) VARIANTS[keepalive]="60"; break ;;
      2) VARIANTS[keepalive]="30"; break ;;
      3) VARIANTS[keepalive]="no"; break ;;
      *) warn "Enter 1, 2, or 3" ;;
    esac
  done

  # ControlPersist (only if multiplexing enabled)
  local mux_enabled=false
  for f in "${ENABLED[@]+"${ENABLED[@]}"}"; do [ "$f" = "multiplexing" ] && mux_enabled=true && break; done

  if [ "$mux_enabled" = "true" ]; then
    echo ""
    info "ControlPersist duration:"
    select cp in "600s (default)" "60s" "indefinite"; do
      case "$REPLY" in
        1) VARIANTS[control_persist]="600"; break ;;
        2) VARIANTS[control_persist]="60";  break ;;
        3) VARIANTS[control_persist]="yes"; break ;;
        *) warn "Enter 1, 2, or 3" ;;
      esac
    done
  else
    VARIANTS[control_persist]="600"
  fi

  # ── Stage 3 — Key generation ───────────────────────────────────────────────
  stage_keygen

  # ── Stage 4 — Write + apply ────────────────────────────────────────────────
  stage_write
}

# ── Dispatch ──────────────────────────────────────────────────────────────────
case "${1:-}" in
  --status)  cmd_status ;;
  --dry-run) DRY_RUN=true; main ;;
  "")        main ;;
  *) error "Unknown flag: ${1}"; echo "Usage: ./ssh-config.sh [--status|--dry-run]" >&2; exit 1 ;;
esac
