#!/usr/bin/env bash
# statusline-customize.sh — Claude Code status line configurator
#
# Usage:
#   ./statusline-customize.sh            # interactive TUI
#   ./statusline-customize.sh --generate # regenerate from config, no TUI
#   ./statusline-customize.sh --status   # print config summary
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_PATH="${STATUSLINE_CONFIG_PATH:-$SCRIPT_DIR/statusline-config.json}"
SKELETON_PATH="$SCRIPT_DIR/statusline-skeleton-config.json"
OUTPUT_PATH="${STATUSLINE_OUTPUT_PATH:-$HOME/.claude/statusline-command.sh}"

# ── Colors ────────────────────────────────────────────────────────────────────
BOLD='\033[1m'
PURPLE='\033[38;2;105;48;122m'
LAVENDER='\033[38;2;239;220;249m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

info()    { echo -e "  ${LAVENDER}${1}${RESET}"; }
success() { echo -e "  ${GREEN}✓${RESET}  ${1}"; }
warn()    { echo -e "  ${YELLOW}!${RESET}  ${1}"; }
error()   { echo -e "  ${RED}✗${RESET}  ${1}" >&2; }
header()  { echo -e "\n${BOLD}${PURPLE}${1}${RESET}"; }

# ── ensure_config ─────────────────────────────────────────────────────────────
# Usage: ensure_config CONFIG_PATH SKELETON_PATH
ensure_config() {
  local cfg="$1" skel="$2"
  if [ ! -f "$cfg" ]; then
    cp "$skel" "$cfg"
    info "Created $(basename "$cfg") from skeleton"
  fi
}

# ── generate_statusline ───────────────────────────────────────────────────────
# Usage: generate_statusline CONFIG_PATH OUTPUT_PATH
generate_statusline() {
  local cfg="$1" out="$2"
  mkdir -p "$(dirname "$out")"
  python3 - "$cfg" "$out" << 'PYEOF'
import json, sys

cfg_path, out_path = sys.argv[1], sys.argv[2]
with open(cfg_path) as f:
    cfg = json.load(f)

palette  = cfg["palette"]
seg_cfg  = cfg.get("segment_config", {})
segments = cfg["segments"]

def ansi(name):
    h = palette[name].lstrip('#')
    r, g, b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    return f"\\033[38;2;{r};{g};{b}m"

def cv(name):
    return f"C_{name.upper()}"

lines = [
    '#!/usr/bin/env bash',
    '# Generated by statusline-customize.sh — edit with: ./statusline-customize.sh',
    'input=$(cat)',
    '',
    'RESET="\\033[0m"',
]

for name, hexval in palette.items():
    h = hexval.lstrip('#')
    r, g, b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    lines.append(f'C_{name.upper()}="\\033[38;2;{r};{g};{b}m"')

lines += ['', 'parts_out=()', '']

for seg in segments:
    sc = seg_cfg.get(seg, {})

    if seg == 'path':
        d  = int(sc.get('max_depth', 3))
        c  = cv(sc.get('color', 'fg'))
        lines += [
            '# path',
            'cwd=$(echo "$input" | jq -r \'.workspace.current_dir // .cwd // empty\')',
            'if [ -n "$cwd" ]; then',
            '  display_path="${cwd/#$HOME/~}"',
            '  IFS=\'/\' read -ra _pp <<< "$display_path"',
            f'  if [ "${{#_pp[@]}}" -gt {d + 1} ]; then',
            f'    display_path="${{_pp[0]}}/${{_pp[1]}}/.../${{_pp[-2]}}/${{_pp[-1]}}"',
            '  fi',
            f'  parts_out+=("$(printf "${{{c}}} %s${{RESET}}" "$display_path")")',
            'fi',
            '',
        ]

    elif seg == 'git':
        show = sc.get('show_changes', True)
        c    = cv(sc.get('color', 'accent'))
        block = [
            '# git',
            '_git_info=""',
            'if _gbr=$(git -C "${cwd:-$PWD}" symbolic-ref --short HEAD 2>/dev/null); then',
        ]
        if show:
            block += [
                '  _wt=$(git -C "${cwd:-$PWD}" status --porcelain 2>/dev/null | wc -l | tr -d \' \')',
                '  _git_info="$_gbr"',
                '  [ "$_wt" -gt 0 ] && _git_info="$_git_info *$_wt"',
            ]
        else:
            block.append('  _git_info="$_gbr"')
        block += [
            'fi',
            'if [ -n "$_git_info" ]; then',
            f'  parts_out+=("$(printf "${{{c}}}$(printf \'\\\\ue0b3\')${{RESET}} ${{C_FG}}%s${{RESET}}" "$_git_info")")',
            'fi',
            '',
        ]
        lines += block

    elif seg == 'vim_mode':
        ic = cv(sc.get('insert_color', 'cyan'))
        nc = cv(sc.get('normal_color', 'yellow'))
        lines += [
            '# vim_mode',
            '_vim=$(echo "$input" | jq -r \'.vim.mode // empty\')',
            'if [ -n "$_vim" ]; then',
            f'  if [ "$_vim" = "NORMAL" ]; then',
            f'    parts_out+=("$(printf "${{{nc}}}NRM${{RESET}}")")',
            f'  else',
            f'    parts_out+=("$(printf "${{{ic}}}INS${{RESET}}")")',
            '  fi',
            'fi',
            '',
        ]

    elif seg == 'model':
        c = cv(sc.get('color', 'dim'))
        lines += [
            '# model',
            '_model=$(echo "$input" | jq -r \'.model.display_name // empty\')',
            'if [ -n "$_model" ]; then',
            f'  parts_out+=("$(printf "${{{c}}}$(printf \'\\\\ue0b3\')${{RESET}} ${{C_FG}}%s${{RESET}}" "$_model")")',
            'fi',
            '',
        ]

    elif seg == 'ctx':
        thr = int(sc.get('warn_threshold', 20))
        c   = cv(sc.get('color', 'cyan'))
        wc  = cv(sc.get('warn_color', 'red'))
        lines += [
            '# ctx',
            '_ctx=$(echo "$input" | jq -r \'.context_window.remaining_percentage // empty\')',
            'if [ -n "$_ctx" ]; then',
            '  _ctx_i=$(printf "%.0f" "$_ctx")',
            f'  if [ "$_ctx_i" -le {thr} ]; then _cc="${{{wc}}}"; else _cc="${{{c}}}"; fi',
            '  parts_out+=("$(printf "$_cc ctx:%s%%${RESET}" "$_ctx_i")")',
            'fi',
            '',
        ]

    elif seg == '5h_pct':
        thr = int(sc.get('warn_threshold', 80))
        c   = cv(sc.get('color', 'yellow'))
        wc  = cv(sc.get('warn_color', 'red'))
        lines += [
            '# 5h_pct',
            '_5h=$(echo "$input" | jq -r \'.rate_limits.five_hour.used_percentage // empty\')',
            'if [ -n "$_5h" ]; then',
            '  _5h_i=$(printf "%.0f" "$_5h")',
            f'  if [ "$_5h_i" -ge {thr} ]; then _5hc="${{{wc}}}"; else _5hc="${{{c}}}"; fi',
            '  parts_out+=("$(printf "$_5hc 5h:%s%%${RESET}" "$_5h_i")")',
            'fi',
            '',
        ]

    elif seg == '5h_tokens':
        thr = int(sc.get('warn_threshold', 80))
        c   = cv(sc.get('color', 'yellow'))
        wc  = cv(sc.get('warn_color', 'red'))
        lines += [
            '# 5h_tokens',
            '_5hu=$(echo "$input" | jq -r \'.rate_limits.five_hour.tokens_used // empty\')',
            '_5hl=$(echo "$input" | jq -r \'.rate_limits.five_hour.tokens_limit // empty\')',
            'if [ -n "$_5hu" ] && [ -n "$_5hl" ] && [ "$_5hl" -gt 0 ]; then',
            '  _5hu_k=$(( _5hu / 1000 ))',
            '  _5hl_k=$(( _5hl / 1000 ))',
            '  _5h_tok_pct=$(( _5hu * 100 / _5hl ))',
            f'  if [ "$_5h_tok_pct" -ge {thr} ]; then _5htc="${{{wc}}}"; else _5htc="${{{c}}}"; fi',
            '  parts_out+=("$(printf "$_5htc 5h:%sk/%sk${RESET}" "$_5hu_k" "$_5hl_k")")',
            'fi',
            '',
        ]

    elif seg == 'weekly':
        thr = int(sc.get('warn_threshold', 80))
        c   = cv(sc.get('color', 'yellow'))
        wc  = cv(sc.get('warn_color', 'red'))
        lines += [
            '# weekly',
            '_wku=$(echo "$input" | jq -r \'.rate_limits.weekly.tokens_used // empty\')',
            '_wkl=$(echo "$input" | jq -r \'.rate_limits.weekly.tokens_limit // empty\')',
            '_wkp=$(echo "$input" | jq -r \'.rate_limits.weekly.used_percentage // empty\')',
            'if [ -n "$_wku" ] && [ -n "$_wkl" ] && [ "$_wkl" -gt 0 ]; then',
            '  _wku_k=$(( _wku / 1000 ))',
            '  _wkl_k=$(( _wkl / 1000 ))',
            '  _wkp_i=$(printf "%.0f" "${_wkp:-0}")',
            f'  if [ "$_wkp_i" -ge {thr} ]; then _wkc="${{{wc}}}"; else _wkc="${{{c}}}"; fi',
            '  parts_out+=("$(printf "$_wkc wk:%sk/%sk${RESET}" "$_wku_k" "$_wkl_k")")',
            'fi',
            '',
        ]

    elif seg == 'reset_5h':
        c = cv(sc.get('color', 'dim'))
        lines += [
            '# reset_5h',
            '_rst5=$(echo "$input" | jq -r \'.rate_limits.five_hour.reset_at // empty\')',
            'if [ -n "$_rst5" ]; then',
            '  _rst5_fmt=$(python3 -c "',
            'import datetime,sys',
            r't=datetime.datetime.fromisoformat(sys.argv[1].replace(\"Z\",\"+00:00\"))',
            'now=datetime.datetime.now(datetime.timezone.utc)',
            'd=int((t-now).total_seconds()/60)',
            r'print(str(d)+\"m\" if d>0 else \"now\")',
            '" "$_rst5" 2>/dev/null || echo "$_rst5")',
            f'  parts_out+=("$(printf "${{{c}}} rst:%s${{RESET}}" "$_rst5_fmt")")',
            'fi',
            '',
        ]

    elif seg == 'reset_weekly':
        c = cv(sc.get('color', 'dim'))
        lines += [
            '# reset_weekly',
            '_rstwk=$(echo "$input" | jq -r \'.rate_limits.weekly.reset_at // empty\')',
            'if [ -n "$_rstwk" ]; then',
            '  _rstwk_fmt=$(python3 -c "',
            'import datetime,sys',
            r't=datetime.datetime.fromisoformat(sys.argv[1].replace(\"Z\",\"+00:00\"))',
            'now=datetime.datetime.now(datetime.timezone.utc)',
            'd=int((t-now).total_seconds()/86400)',
            r'print(str(d)+\"d\" if d>0 else \"today\")',
            '" "$_rstwk" 2>/dev/null || echo "$_rstwk")',
            f'  parts_out+=("$(printf "${{{c}}} rst-wk:%s${{RESET}}" "$_rstwk_fmt")")',
            'fi',
            '',
        ]

    elif seg == 'cost':
        thr = float(sc.get('warn_threshold', 5.0))
        c   = cv(sc.get('color', 'fg'))
        wc  = cv(sc.get('warn_color', 'red'))
        lines += [
            '# cost',
            '_cost=$(echo "$input" | jq -r \'.billing.session_cost // empty\')',
            'if [ -n "$_cost" ]; then',
            f'  _cost_warn=$(python3 -c "import sys; print(1 if float(sys.argv[1]) >= {thr} else 0)" "$_cost" 2>/dev/null || echo 0)',
            f'  if [ "$_cost_warn" = "1" ]; then _costc="${{{wc}}}"; else _costc="${{{c}}}"; fi',
            r'  parts_out+=("$(printf "$_costc \$%.2f${RESET}" "$_cost")")',
            'fi',
            '',
        ]

    elif seg == 'mode':
        pc = cv(sc.get('plan_color',   'cyan'))
        ac = cv(sc.get('auto_color',   'yellow'))
        nc = cv(sc.get('normal_color', 'dim'))
        lines += [
            '# mode',
            '_mode=$(echo "$input" | jq -r \'.mode // empty\')',
            'if [ -n "$_mode" ]; then',
            '  case "$_mode" in',
            f'    plan) _modec="${{{pc}}}" ;;',
            f'    auto) _modec="${{{ac}}}" ;;',
            f'    *)    _modec="${{{nc}}}" ;;',
            '  esac',
            '  parts_out+=("$(printf "$_modec %s${RESET}" "$_mode")")',
            'fi',
            '',
        ]

lines += [
    'printf "%b" "$(IFS=\' \'; echo "${parts_out[*]}")"',
    'printf "\\n"',
]

with open(out_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')
PYEOF
}

# ── cmd_status ────────────────────────────────────────────────────────────────
cmd_status() {
  header "Statusline Configuration"
  if [ ! -f "$CONFIG_PATH" ]; then
    warn "No config found at $CONFIG_PATH — run ./statusline-customize.sh to create one"
    return 0
  fi
  local segs
  segs=$(python3 - "$CONFIG_PATH" << 'PYEOF'
import json, sys
c = json.load(open(sys.argv[1]))
print(', '.join(c['segments']))
PYEOF
)
  success "Active segments: $segs"
  info "Config: $CONFIG_PATH"
  info "Output: $OUTPUT_PATH"
}

# ── tui_stage1_toggle ─────────────────────────────────────────────────────────
tui_stage1_toggle() {
  local config="$1"
  local all_segs="path git vim_mode model ctx 5h_pct 5h_tokens weekly reset_5h reset_weekly cost mode"
  local enabled
  enabled=$(python3 - "$config" << 'PYEOF'
import json, sys
c = json.load(open(sys.argv[1]))
print('\n'.join(c['segments']))
PYEOF
)

  # Build fzf start binding to pre-select currently enabled segments
  local start_binding=""
  while IFS= read -r seg; do
    [ -z "$seg" ] && continue
    [ -n "$start_binding" ] && start_binding+="+"
    start_binding+="select($seg)"
  done <<< "$enabled"

  local selected
  selected=$(printf '%s\n' $all_segs | fzf --multi \
    --header="Highlighted = enabled  |  Tab/Space=toggle  Enter=confirm  Esc=cancel" \
    --prompt="Segments > " \
    ${start_binding:+--bind "start:$start_binding"}) || { info "Segment selection cancelled — keeping current"; return 1; }

  if [ -z "$selected" ]; then
    info "No segments selected — keeping current"
    return 1
  fi

  # Collect selected segment names
  local new_segs=()
  while IFS= read -r seg; do
    [ -n "$seg" ] && new_segs+=("$seg")
  done <<< "$selected"

  # Reorder loop — pick next segment in desired order
  local ordered=()
  local remaining=("${new_segs[@]}")
  local total="${#remaining[@]}"
  local i=1
  while [ "${#remaining[@]}" -gt 0 ]; do
    local pick
    pick=$(printf '%s\n' "${remaining[@]}" | fzf \
      --header="Pick segment $i of $total (in display order)" \
      --prompt="Order > ") || { info "Reorder cancelled — using toggle order"; ordered=("${new_segs[@]}"); break; }
    ordered+=("$pick")
    # Remove picked item from remaining
    local new_remaining=()
    for s in "${remaining[@]}"; do
      [ "$s" != "$pick" ] && new_remaining+=("$s")
    done
    remaining=("${new_remaining[@]}")
    (( i++ )) || true
  done

  # Update segments array in config
  python3 - "$config" "${ordered[@]}" << 'PYEOF'
import json, sys
cfg_path = sys.argv[1]
new_segs = sys.argv[2:]
with open(cfg_path) as f:
    cfg = json.load(f)
cfg["segments"] = new_segs
with open(cfg_path, 'w') as f:
    json.dump(cfg, f, indent=2)
PYEOF
}

# ── tui_stage2_config ─────────────────────────────────────────────────────────
tui_stage2_config() {
  local config="$1"
  local palette_names="fg accent cyan yellow dim red lavender"
  local preset_thresholds="10 15 20 25 30 50 80"

  local segments
  segments=$(python3 - "$config" << 'PYEOF'
import json, sys
c = json.load(open(sys.argv[1]))
print('\n'.join(c['segments']))
PYEOF
)

  while IFS= read -r seg; do
    local options=()
    case "$seg" in
      path)     options=("max_depth" "color") ;;
      git)      options=("show_changes" "color") ;;
      vim_mode) options=("insert_color" "normal_color") ;;
      model)    options=("color") ;;
      ctx)      options=("warn_threshold" "color" "warn_color") ;;
      5h_pct)   options=("warn_threshold" "color" "warn_color") ;;
      5h_tokens) options=("warn_threshold" "color" "warn_color") ;;
      weekly)   options=("warn_threshold" "color" "warn_color") ;;
      reset_5h|reset_weekly) options=("color") ;;
      cost)     options=("warn_threshold" "color" "warn_color") ;;
      mode)     options=("plan_color" "auto_color" "normal_color") ;;
    esac

    # Inner loop: keep showing option menu until user presses Escape
    while true; do
      # Build option menu with current values
      local menu=""
      for opt in "${options[@]}"; do
        local cur
        cur=$(python3 - "$config" "$seg" "$opt" << 'PYEOF'
import json, sys
c = json.load(open(sys.argv[1]))
val = c.get('segment_config', {}).get(sys.argv[2], {}).get(sys.argv[3], '—')
print(val)
PYEOF
2>/dev/null || echo "—")
        menu+="$opt    [current: $cur]\n"
      done

      local chosen_opt
      chosen_opt=$(printf "%b" "$menu" | fzf \
        --header="Configure: $seg  (Esc=done with this segment)" \
        --prompt="Option > ") || break  # Escape exits inner loop, moves to next segment

      local opt_name="${chosen_opt%%    *}"

      # Pick new value
      local new_val
      case "$opt_name" in
        *color*)
          new_val=$(printf '%s\n' $palette_names | fzf \
            --header="Pick color for $seg.$opt_name" \
            --prompt="Color > ") || continue
          ;;
        warn_threshold|max_depth)
          new_val=$(printf '%s\n' $preset_thresholds | fzf \
            --print-query \
            --header="Pick threshold (or type custom value)" \
            --prompt="Value > " | tail -1) || continue
          ;;
        show_changes)
          new_val=$(printf 'true\nfalse\n' | fzf \
            --header="Show change count?" \
            --prompt="> ") || continue
          ;;
      esac

      # Write new value to config
      python3 - "$config" "$seg" "$opt_name" "$new_val" << 'PYEOF'
import json, sys
cfg_path, seg, opt, val = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
with open(cfg_path) as f:
    cfg = json.load(f)
if "segment_config" not in cfg:
    cfg["segment_config"] = {}
if seg not in cfg["segment_config"]:
    cfg["segment_config"][seg] = {}
# Type coercion
if val in ("true", "false"):
    val = val == "true"
elif val.lstrip('-').isdigit():
    val = int(val)
elif '.' in val:
    try:
        val = float(val)
    except ValueError:
        pass
cfg["segment_config"][seg][opt] = val
with open(cfg_path, 'w') as f:
    json.dump(cfg, f, indent=2)
PYEOF
      info "$seg.$opt_name → $new_val"
    done  # end inner while loop for this segment
  done <<< "$segments"
}

# ── tui_stage3_preview ────────────────────────────────────────────────────────
tui_stage3_preview() {
  local config="$1"
  local tmp_script
  tmp_script=$(mktemp /tmp/statusline-preview-XXXXXX.sh)
  trap 'rm -f "$tmp_script"' RETURN

  generate_statusline "$config" "$tmp_script"

  local mock_json='{"workspace":{"current_dir":"/Users/demo/code/dotfiles"},"model":{"display_name":"claude-sonnet-4-6"},"context_window":{"remaining_percentage":84},"rate_limits":{"five_hour":{"used_percentage":42,"tokens_used":12000,"tokens_limit":40000}},"vim":{"mode":"INSERT"},"mode":"normal"}'
  echo ""
  header "Preview"
  echo "$mock_json" | bash "$tmp_script" || warn "Preview render failed"
  echo ""

  local confirm
  confirm=$(printf 'Apply\nCancel\n' | fzf \
    --header="Apply this configuration?" \
    --prompt="> ") || return 1

  [ "$confirm" = "Apply" ]
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  command -v fzf >/dev/null 2>&1 || { error "fzf not found — install with: brew install fzf"; exit 1; }
  command -v python3 >/dev/null 2>&1 || { error "python3 not found — install python3 to use this tool"; exit 1; }

  ensure_config "$CONFIG_PATH" "$SKELETON_PATH"

  header "Statusline Customizer"
  info "Config: $CONFIG_PATH"

  # Stage 1: toggle + reorder
  echo ""
  info "Stage 1: Toggle and order segments"
  tui_stage1_toggle "$CONFIG_PATH" || { info "Cancelled."; exit 0; }

  # Stage 2: per-segment config
  echo ""
  info "Stage 2: Configure each segment"
  tui_stage2_config "$CONFIG_PATH"

  # Stage 3: preview + apply
  if tui_stage3_preview "$CONFIG_PATH"; then
    mkdir -p "$(dirname "$OUTPUT_PATH")"
    generate_statusline "$CONFIG_PATH" "$OUTPUT_PATH"
    success "Written to $OUTPUT_PATH"
    success "Done. Status line updated — takes effect immediately."
  else
    info "Cancelled — no changes applied."
    info "Config edits saved to $CONFIG_PATH (run again to apply)"
  fi
}

# ── Source-only guard (place after ALL function definitions) ──────────────────
[ "${STATUSLINE_CUSTOMIZE_SOURCE_ONLY:-}" = "1" ] && return 0

# ── Dispatch ──────────────────────────────────────────────────────────────────
if [ $# -gt 1 ]; then
  echo "Usage: statusline-customize.sh [--generate|--status]" >&2; exit 1
fi
case "${1:-}" in
  --status)   cmd_status; exit 0 ;;
  --generate)
    ensure_config "$CONFIG_PATH" "$SKELETON_PATH"
    mkdir -p "$(dirname "$OUTPUT_PATH")"
    generate_statusline "$CONFIG_PATH" "$OUTPUT_PATH"
    success "Generated $OUTPUT_PATH"
    ;;
  "") main ;;
  *)  echo "Usage: statusline-customize.sh [--generate|--status]" >&2; exit 1 ;;
esac
