#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=platform.sh
. "$SCRIPT_DIR/platform.sh"

# ── Argument parsing ──────────────────────────────────────────────────────────
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
  esac
done

# ── Colors ───────────────────────────────────────────────────────────────────
BOLD='\033[1m'
PURPLE='\033[38;2;105;48;122m'
LAVENDER='\033[38;2;239;220;249m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

info()    { echo -e "  ${LAVENDER}${1}${RESET}"; }
success() { echo -e "  ${GREEN}✓${RESET}  ${1}"; }
warn()    { echo -e "  ${YELLOW}!${RESET}  ${1}"; }
header()  { echo -e "\n${BOLD}${PURPLE}${1}${RESET}"; }

# ── run_cmd ───────────────────────────────────────────────────────────────────
# Wraps file-write operations for --dry-run support.
# In dry-run mode, prints the command instead of executing it.
run_cmd() {
  if [ "$DRY_RUN" = "true" ]; then
    echo "  $*"
  else
    "$@"
  fi
}

# ── is_enabled <key> ──────────────────────────────────────────────────────────
# Returns 0 if key is in ENABLED array, 1 otherwise.
is_enabled() {
  local key="$1" k
  for k in "${ENABLED[@]+"${ENABLED[@]}"}"; do
    [ "$k" = "$key" ] && return 0
  done
  return 1
}

# ── write_to_local <text> ─────────────────────────────────────────────────────
# Appends text to LOCAL_CONF_OUT (string buffer) during write_local_conf().
write_to_local() { LOCAL_CONF_OUT+="${1}"$'\n'; }

# ── write_to_plugins <text> ───────────────────────────────────────────────────
# Appends text to PLUGINS_CONF_OUT (string buffer) during write_plugins_conf().
write_to_plugins() { PLUGINS_CONF_OUT+="${1}"$'\n'; }

# ── write_plugins_conf ────────────────────────────────────────────────────────
# Generates ~/.tmux.conf.plugins content.
# Reads: ENABLED[], DRY_RUN
# Output is buffered in PLUGINS_CONF_OUT for dry-run; written to file otherwise.
write_plugins_conf() {
  PLUGINS_CONF_OUT=""
  local ts
  ts="$(date '+%Y-%m-%d %H:%M:%S')"

  write_to_plugins "# ~/.tmux.conf.plugins — generated by tmux-config.sh"
  write_to_plugins "# Generated: $ts"
  write_to_plugins "# Re-run ./tmux-config.sh to regenerate."

  if is_enabled "persistence"; then
    write_to_plugins ""
    write_to_plugins "set -g @plugin 'tmux-plugins/tmux-resurrect'"
    write_to_plugins "set -g @plugin 'tmux-plugins/tmux-continuum'"
    write_to_plugins "set -g @resurrect-capture-pane-contents 'on'"
    write_to_plugins "set -g @continuum-restore 'on'"
    write_to_plugins "set -g @continuum-save-interval '15'"
  else
    write_to_plugins ""
    write_to_plugins "# Session persistence disabled — re-run ./tmux-config.sh to enable."
  fi

  if [ "$DRY_RUN" = "true" ]; then
    echo "# --- ~/.tmux.conf.plugins ---"
    echo "$PLUGINS_CONF_OUT"
    return
  fi

  local plugins_file="$HOME/.tmux.conf.plugins"
  if [ -f "$plugins_file" ]; then
    cp "$plugins_file" "${plugins_file}.backup.$(date +%Y%m%d%H%M%S)"
  fi
  printf '%s\n' "$PLUGINS_CONF_OUT" > "$plugins_file"
  success "Written: $plugins_file"
}

# ── write_plugins_conf_safe_default ──────────────────────────────────────────
# Called on skip/non-interactive: writes plugins file with persistence enabled
# only if it does not already exist.
write_plugins_conf_safe_default() {
  local plugins_file="$HOME/.tmux.conf.plugins"
  if [ -f "$plugins_file" ]; then
    return  # already exists — leave untouched
  fi
  ENABLED=(persistence)
  DISABLED=()
  write_plugins_conf
}

# ── write_local_conf ──────────────────────────────────────────────────────────
# Generates ~/.tmux.conf.local content.
# Reads: ENABLED[], DISABLED[], VARIANTS{}, DRY_RUN, DOTFILES_OS
write_local_conf() {
  LOCAL_CONF_OUT=""
  local ts
  ts="$(date '+%Y-%m-%d %H:%M:%S')"

  write_to_local "# ~/.tmux.conf.local — generated by tmux-config.sh"
  write_to_local "# Generated: $ts"
  write_to_local "# Re-run ./tmux-config.sh to regenerate (backs up this file first)."
  write_to_local "# Delete this file to restore base config defaults."

  # ── Prefix ──────────────────────────────────────────────────────────────────
  if [ "${VARIANTS[prefix]:-C-a}" = "C-b" ]; then
    write_to_local ""
    write_to_local "# ── Prefix ───────────────────────────────────────────────────────────────────"
    write_to_local "unbind C-a"
    write_to_local "set -g prefix C-b"
    write_to_local "bind C-b send-prefix"
  fi

  # ── Mouse ───────────────────────────────────────────────────────────────────
  if ! is_enabled "mouse"; then
    write_to_local ""
    write_to_local "# ── Mouse ────────────────────────────────────────────────────────────────────"
    write_to_local "set -g mouse off"
  fi

  # ── Smart scroll ────────────────────────────────────────────────────────────
  if ! is_enabled "smart_scroll"; then
    write_to_local ""
    write_to_local "# ── Smart scroll (pass-through disabled) ─────────────────────────────────────"
    write_to_local "unbind -n WheelUpPane"
    write_to_local "unbind -n WheelDownPane"
  fi

  # ── Vim nav ─────────────────────────────────────────────────────────────────
  if ! is_enabled "vim_nav"; then
    write_to_local ""
    write_to_local "# ── Pane navigation ──────────────────────────────────────────────────────────"
    write_to_local "unbind h"
    write_to_local "unbind j"
    write_to_local "unbind k"
    write_to_local "unbind l"
  fi

  # ── Vi copy mode ────────────────────────────────────────────────────────────
  if ! is_enabled "vi_copy"; then
    write_to_local ""
    write_to_local "# ── Copy mode ────────────────────────────────────────────────────────────────"
    write_to_local "setw -g mode-keys emacs"
  fi

  # ── Clipboard ───────────────────────────────────────────────────────────────
  # Always written on Linux (base config has pbcopy hardcoded).
  # Written on macOS if: clipboard disabled, or copy_cmd differs from pbcopy.
  local copy_cmd="${VARIANTS[copy_cmd]:-pbcopy}"
  local write_clipboard=false
  if ! is_enabled "clipboard"; then
    write_clipboard=true
  elif [ "$DOTFILES_OS" = "linux" ]; then
    write_clipboard=true
  elif [ "$copy_cmd" != "pbcopy" ]; then
    write_clipboard=true
  fi

  if [ "$write_clipboard" = "true" ]; then
    write_to_local ""
    write_to_local "# ── Clipboard ────────────────────────────────────────────────────────────────"
    if is_enabled "clipboard" && [ -n "$copy_cmd" ]; then
      write_to_local "bind -T copy-mode-vi y send -X copy-pipe-and-cancel \"$copy_cmd\""
      write_to_local "bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel \"$copy_cmd\""
    else
      write_to_local "unbind -T copy-mode-vi y"
      write_to_local "unbind -T copy-mode-vi MouseDragEnd1Pane"
    fi
  fi

  # ── Scrollback ──────────────────────────────────────────────────────────────
  local scrollback="${VARIANTS[scrollback]:-10000}"
  if [ "$scrollback" != "10000" ]; then
    write_to_local ""
    write_to_local "# ── Scrollback ───────────────────────────────────────────────────────────────"
    write_to_local "set -g history-limit $scrollback"
  fi

  # ── Pane border style ───────────────────────────────────────────────────────
  local border_style="${VARIANTS[border_style]:-double}"
  if [ "$border_style" != "double" ]; then
    write_to_local ""
    write_to_local "# ── Pane border style ────────────────────────────────────────────────────────"
    write_to_local "set -g pane-border-lines $border_style"
  fi

  # ── Border labels ───────────────────────────────────────────────────────────
  if ! is_enabled "border_labels"; then
    write_to_local ""
    write_to_local "# ── Border labels ────────────────────────────────────────────────────────────"
    write_to_local "set -g pane-border-status off"
  fi

  # Status bar is handled in a separate call — see _write_local_status_bar()
  _write_local_status_bar

  if [ "$DRY_RUN" = "true" ]; then
    echo "# --- ~/.tmux.conf.local ---"
    echo "$LOCAL_CONF_OUT"
    return
  fi

  local local_file="$HOME/.tmux.conf.local"
  if [ -f "$local_file" ]; then
    cp "$local_file" "${local_file}.backup.$(date +%Y%m%d%H%M%S)"
  fi
  printf '%s\n' "$LOCAL_CONF_OUT" > "$local_file"
  success "Written: $local_file"
}

_write_local_status_bar() {
  local style="${VARIANTS[statusbar_style]:-themed}"
  local np_pos="${VARIANTS[nowplaying_pos]:-right}"
  local cl_pos="${VARIANTS[clock_pos]:-right}"
  local np_on=false; local cl_on=false
  is_enabled "nowplaying" && np_on=true
  is_enabled "clock"      && cl_on=true

  # ── Minimal style ─────────────────────────────────────────────────────────
  if [ "$style" = "minimal" ]; then
    write_to_local ""
    write_to_local "# ── Status bar (minimal) ─────────────────────────────────────────────────────"
    write_to_local "set -g status-left \" #S \""
    write_to_local "set -g status-left-length 20"
    write_to_local "set -g status-right \" %H:%M \""
    write_to_local "set -g status-right-length 15"
    return
  fi

  # ── Themed style — check if any positional override is needed ─────────────
  # Base default: nowplaying=right, clock=right (both enabled). No override needed.
  local need_override=false
  if [ "$np_on" = "true" ] && [ "$cl_on" = "true" ]; then
    if [ "$np_pos" != "right" ] || [ "$cl_pos" != "right" ]; then
      need_override=true
    fi
  elif [ "$np_on" = "false" ] || [ "$cl_on" = "false" ]; then
    # Any disabled widget requires overriding the status bar
    need_override=true
  fi

  [ "$need_override" = "false" ] && return

  write_to_local ""
  write_to_local "# ── Status bar ───────────────────────────────────────────────────────────────"

  local NP="#(\$HOME/.tmux/now-playing.sh)"
  local CL="#[fg=#4c1f5e]\ue0b6#[bg=#4c1f5e,fg=#EFDCF9]  %H:%M "
  local NP_SEG="#[fg=#341948]\ue0b6#[bg=#341948,fg=#EFDCF9] $NP "
  local BASE_LEFT="#[bg=#69307A,fg=#EFDCF9,bold]  #S #[bg=#170B3B,fg=#69307A]\ue0b4"

  if [ "$np_on" = "true" ] && [ "$cl_on" = "true" ]; then
    # np-right, clock-left
    if [ "$np_pos" = "right" ] && [ "$cl_pos" = "left" ]; then
      write_to_local "set -g status-left \"${BASE_LEFT} ${CL}\""
      write_to_local "set -g status-left-length 50"
      write_to_local "set -g status-right \"${NP_SEG}\""
      write_to_local "set -g status-right-length 60"
    # np-left, clock-right
    elif [ "$np_pos" = "left" ] && [ "$cl_pos" = "right" ]; then
      write_to_local "set -g status-left \"${BASE_LEFT} ${NP_SEG}\""
      write_to_local "set -g status-left-length 80"
      write_to_local "set -g status-right \"${CL}\""
      write_to_local "set -g status-right-length 15"
    # both left
    else
      write_to_local "set -g status-left \"${BASE_LEFT} ${NP_SEG} ${CL}\""
      write_to_local "set -g status-left-length 100"
      write_to_local "set -g status-right \"\""
      write_to_local "set -g status-right-length 0"
    fi
  elif [ "$np_on" = "false" ] && [ "$cl_on" = "true" ]; then
    if [ "$cl_pos" = "right" ]; then
      write_to_local "set -g status-right \"${CL}\""
      write_to_local "set -g status-right-length 15"
    else
      # clock left
      write_to_local "set -g status-left \"${BASE_LEFT} ${CL}\""
      write_to_local "set -g status-left-length 60"
      write_to_local "set -g status-right \"\""
      write_to_local "set -g status-right-length 0"
    fi
  else
    # both off
    write_to_local "set -g status-right \"\""
    write_to_local "set -g status-right-length 0"
  fi
}

# ── Toggle catalog ────────────────────────────────────────────────────────────
# All toggle labels in display order. nowplaying excluded on Linux at runtime.
_ALL_TOGGLES=(
  "[Mouse]       Enable mouse support|mouse"
  "[Mouse]       Smart scroll (pass-through for vim/less)|smart_scroll"
  "[Navigation]  Vim-style pane nav (h/j/k/l)|vim_nav"
  "[Copy]        Vi copy mode keys|vi_copy"
  "[Copy]        Clipboard integration|clipboard"
  "[Status Bar]  Now-playing widget|nowplaying"
  "[Status Bar]  Clock|clock"
  "[Pane]        Border labels (index + current command)|border_labels"
  "[Session]     Session persistence (resurrect + continuum)|persistence"
)

# ── _apply_preset <full|minimal> ──────────────────────────────────────────────
# Pre-populates ENABLED[] and DISABLED[] from a named preset.
_apply_preset() {
  local preset="$1"
  ENABLED=()
  DISABLED=()
  case "$preset" in
    full)
      for entry in "${_ALL_TOGGLES[@]}"; do
        local key="${entry##*|}"
        [ "$key" = "nowplaying" ] && [ "$DOTFILES_OS" != "macos" ] && continue
        ENABLED+=("$key")
      done
      ;;
    minimal)
      # enabled: mouse smart_scroll vim_nav vi_copy clipboard clock
      # disabled: nowplaying border_labels persistence
      ENABLED=(mouse smart_scroll vim_nav vi_copy clipboard clock)
      DISABLED=(nowplaying border_labels persistence)
      ;;
  esac
}

# ── fzf_toggle_stage ──────────────────────────────────────────────────────────
# Runs Stage 1. Populates ENABLED[] and DISABLED[].
# Uses fzf if available; falls back to select preset menu.
fzf_toggle_stage() {
  ENABLED=(); DISABLED=()

  if ! command -v fzf >/dev/null 2>&1; then
    warn "fzf not found — install it for per-feature selection (tools-config.sh installs it automatically)"
    echo ""
    local choice
    PS3="  Choose a preset: "
    select choice in \
      "Full — all features enabled, current defaults" \
      "Minimal — mouse on, vim nav on, no status bar bling, no persistence" \
      "Skip — no customisation"; do
      case "$REPLY" in
        1) _apply_preset "full";    break ;;
        2) _apply_preset "minimal"; break ;;
        3) ENABLED=(); DISABLED=(); return 1 ;;  # signal skip
        *) echo "  Enter 1, 2, or 3." ;;
      esac
    done || true  # guard against Ctrl-D
    return 0
  fi

  # Build fzf input — one label per line, nowplaying excluded on Linux
  local labels=()
  for entry in "${_ALL_TOGGLES[@]}"; do
    local label="${entry%%|*}"
    local key="${entry##*|}"
    [ "$key" = "nowplaying" ] && [ "$DOTFILES_OS" != "macos" ] && continue
    labels+=("$label")
  done

  local selected
  selected="$(printf '%s\n' "${labels[@]}" \
    | fzf --multi \
          --prompt "Toggle features > " \
          --header "Space/Tab to toggle · Enter to confirm · Esc to skip" \
          --height "80%" \
          --reverse \
          --bind "start:select-all" \
    || true)"

  # Map selected labels back to keys
  for entry in "${_ALL_TOGGLES[@]}"; do
    local label="${entry%%|*}"
    local key="${entry##*|}"
    [ "$key" = "nowplaying" ] && [ "$DOTFILES_OS" != "macos" ] && continue
    if echo "$selected" | grep -qF "$label"; then
      ENABLED+=("$key")
    else
      DISABLED+=("$key")
    fi
  done
}

# ── _set_variant_defaults ─────────────────────────────────────────────────────
_set_variant_defaults() {
  declare -gA VARIANTS
  VARIANTS[prefix]="C-a"
  VARIANTS[border_style]="double"
  VARIANTS[statusbar_style]="themed"
  VARIANTS[scrollback]="10000"
  VARIANTS[copy_cmd]="auto"
  VARIANTS[clock_pos]="right"
  VARIANTS[nowplaying_pos]="right"
}

# ── _resolve_copy_cmd ─────────────────────────────────────────────────────────
# Resolves "auto" to the platform copy command.
# Sets VARIANTS[copy_cmd] in place.
_resolve_copy_cmd() {
  if [ "${VARIANTS[copy_cmd]}" != "auto" ]; then
    return
  fi
  if [ "$DOTFILES_OS" = "macos" ]; then
    VARIANTS[copy_cmd]="pbcopy"
  elif command -v xclip >/dev/null 2>&1; then
    VARIANTS[copy_cmd]="xclip -selection clipboard"
  elif command -v xsel >/dev/null 2>&1; then
    VARIANTS[copy_cmd]="xsel --clipboard --input"
  else
    warn "No clipboard tool found (xclip/xsel) — clipboard integration will be skipped"
    VARIANTS[copy_cmd]=""
  fi
}

# ── variant_stage ─────────────────────────────────────────────────────────────
# Runs Stage 2. Populates VARIANTS{} based on user selections.
# select loops guard against Ctrl-D with || true.
variant_stage() {
  _set_variant_defaults

  # Prefix key
  local choice
  PS3="  Prefix key: "
  select choice in "Ctrl+a (current default)" "Ctrl+b (tmux upstream default)"; do
    case "$REPLY" in
      1) VARIANTS[prefix]="C-a"; break ;;
      2) VARIANTS[prefix]="C-b"; break ;;
      *) echo "  Enter 1 or 2." ;;
    esac
  done || true

  # Pane border style
  PS3="  Pane border style: "
  select choice in "Double (current)" "Single" "Heavy"; do
    case "$REPLY" in
      1) VARIANTS[border_style]="double"; break ;;
      2) VARIANTS[border_style]="single"; break ;;
      3) VARIANTS[border_style]="heavy";  break ;;
      *) echo "  Enter 1, 2, or 3." ;;
    esac
  done || true

  # Status bar style
  PS3="  Status bar style: "
  select choice in "Themed velvet (current)" "Minimal (no powerline glyphs)"; do
    case "$REPLY" in
      1) VARIANTS[statusbar_style]="themed";  break ;;
      2) VARIANTS[statusbar_style]="minimal"; break ;;
      *) echo "  Enter 1 or 2." ;;
    esac
  done || true

  # Scrollback buffer
  PS3="  Scrollback buffer: "
  select choice in "10,000 lines (current)" "50,000 lines" "Unlimited"; do
    case "$REPLY" in
      1) VARIANTS[scrollback]="10000"; break ;;
      2) VARIANTS[scrollback]="50000"; break ;;
      3) VARIANTS[scrollback]="0";     break ;;
      *) echo "  Enter 1, 2, or 3." ;;
    esac
  done || true

  # Copy command (only if clipboard enabled)
  if is_enabled "clipboard"; then
    PS3="  Copy command: "
    select choice in "Auto-detect" "pbcopy (macOS)" "xclip (Linux)" "xsel (Linux)"; do
      case "$REPLY" in
        1) VARIANTS[copy_cmd]="auto";  break ;;
        2) VARIANTS[copy_cmd]="pbcopy"; break ;;
        3) VARIANTS[copy_cmd]="xclip -selection clipboard"; break ;;
        4) VARIANTS[copy_cmd]="xsel --clipboard --input";   break ;;
        *) echo "  Enter 1, 2, 3, or 4." ;;
      esac
    done || true
    _resolve_copy_cmd
  fi

  # Now-playing position (macOS + enabled only)
  if [ "$DOTFILES_OS" = "macos" ] && is_enabled "nowplaying"; then
    PS3="  Now-playing position: "
    select choice in "Right side (current)" "Left side"; do
      case "$REPLY" in
        1) VARIANTS[nowplaying_pos]="right"; break ;;
        2) VARIANTS[nowplaying_pos]="left";  break ;;
        *) echo "  Enter 1 or 2." ;;
      esac
    done || true
  fi

  # Clock position (only if clock enabled)
  if is_enabled "clock"; then
    PS3="  Clock position: "
    select choice in "Right side (current)" "Left side"; do
      case "$REPLY" in
        1) VARIANTS[clock_pos]="right"; break ;;
        2) VARIANTS[clock_pos]="left";  break ;;
        *) echo "  Enter 1 or 2." ;;
      esac
    done || true
  fi
}

# ── tmux_customise ────────────────────────────────────────────────────────────
# Orchestrates Stage 1 + Stage 2 + file writes.
tmux_customise() {
  header "tmux Customisation"

  # Stage 1: toggle checklist
  fzf_toggle_stage || {
    info "Skipping customisation — base config applied."
    write_plugins_conf_safe_default
    return
  }

  if [ "${#ENABLED[@]}" -eq 0 ] && [ "${#DISABLED[@]}" -eq 0 ]; then
    info "No features selected — skipping customisation."
    write_plugins_conf_safe_default
    return
  fi

  # Stage 2: variant menus
  variant_stage

  header "Writing configuration"
  write_local_conf
  write_plugins_conf

  # Notify if persistence state changed
  local current_has_resurrect=false
  [ -f "$HOME/.tmux.conf.plugins" ] && grep -q "tmux-resurrect" "$HOME/.tmux.conf.plugins" 2>/dev/null && current_has_resurrect=true || true
  local new_has_resurrect=false
  is_enabled "persistence" && new_has_resurrect=true

  if [ "$current_has_resurrect" != "$new_has_resurrect" ]; then
    echo ""
    warn "Restart your tmux server for plugin changes to take effect:"
    warn "  tmux kill-server && tmux"
  fi

  echo ""
  success "tmux customisation complete."
  info "Reload config in a running session: Ctrl+a then r"
}

# ── Source-only guard (for testing) ──────────────────────────────────────────
# Set TMUX_CONFIG_SOURCE_ONLY=1 to source this file without executing install logic.
if [ "${TMUX_CONFIG_SOURCE_ONLY:-}" != "1" ]; then

TMUX_CONF="$HOME/.tmux.conf"
BACKUP="$TMUX_CONF.backup.$(date +%Y%m%d%H%M%S)"

# Install tmux if missing
if ! command -v tmux >/dev/null 2>&1; then
  echo "Installing tmux..."
  $PKG_INSTALL "$(pkg tmux)"
else
  echo "tmux already installed: $(tmux -V)"
fi

# Install nowplaying-cli (macOS only — no Linux equivalent)
if [ "$DOTFILES_OS" = "macos" ]; then
  if ! command -v nowplaying-cli >/dev/null 2>&1; then
    echo "Installing nowplaying-cli via Homebrew..."
    brew install nowplaying-cli
  else
    echo "nowplaying-cli already installed"
  fi
fi

# Back up existing config if it's a regular file (not already a symlink)
if [ -f "$TMUX_CONF" ] && [ ! -L "$TMUX_CONF" ]; then
  echo "Backing up $TMUX_CONF to $BACKUP"
  cp "$TMUX_CONF" "$BACKUP"
fi

# Symlink configs into place
echo "Linking tmux.conf → $TMUX_CONF"
ln -sf "$SCRIPT_DIR/tmux.conf" "$TMUX_CONF"

if [ "$DOTFILES_OS" = "macos" ]; then
  mkdir -p "$HOME/.tmux"
  echo "Linking now-playing.sh → $HOME/.tmux/now-playing.sh"
  ln -sf "$SCRIPT_DIR/now-playing.sh" "$HOME/.tmux/now-playing.sh"
  chmod +x "$SCRIPT_DIR/now-playing.sh"
fi

# ── Customisation prompt ────────────────────────────────────────────────────
echo ""
if [ "$DRY_RUN" = "true" ]; then
  info "(dry-run mode — no files will be written)"
  tmux_customise
elif [ -t 0 ]; then
  printf "  Customise tmux settings? [Y/n] "
  read -r reply || true
  case "${reply:-y}" in
    [Nn]*) info "Skipping customisation — base config applied."
           write_plugins_conf_safe_default ;;
    *)     tmux_customise ;;
  esac
else
  info "Non-interactive — skipping tmux customisation."
  write_plugins_conf_safe_default
fi

fi
