# Powerlevel10k config — Catppuccin Mocha
#
# Palette:
#   #1e1e2e  base (background)
#   #313244  surface0 (dir bg, right segment bg)
#   #45475a  surface1 (git bg)
#   #585b70  surface2 (exec time bg)
#   #cdd6f4  text (foreground)
#   #cba6f7  mauve (prompt char insert)
#   #89b4fa  blue (status ok bg)
#   #a6e3a1  green (node)
#   #f9e2af  yellow (python, untracked)
#   #f38ba8  red (status error, ruby, java, modified)

typeset -g POWERLEVEL9K_MODE='nerdfont-complete'

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon dir vcs command_execution_time status newline prompt_char
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  virtualenv pyenv goenv nvm rbenv java_version time
)

typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=' '

typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#1e1e2e'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#cdd6f4'

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=30
typeset -g POWERLEVEL9K_HOME_ICON=''
typeset -g POWERLEVEL9K_HOME_SUB_ICON=''
typeset -g POWERLEVEL9K_FOLDER_ICON=''
typeset -g POWERLEVEL9K_ETC_ICON=''

typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#45475a'
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#45475a'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#45475a'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0.5
typeset -g POWERLEVEL9K_VCS_STAGED_MAX_NUM=99
typeset -g POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=99

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='#585b70'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='duration'

typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND='#89b4fa'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#1e1e2e'
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='\uF08A'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND='#89b4fa'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#1e1e2e'
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#f38ba8'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#1e1e2e'
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='\uF08A'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND='#f38ba8'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#1e1e2e'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION='V'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION='❮'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#cba6f7'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

typeset -g POWERLEVEL9K_PYENV_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_PYENV_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_PYENV_VISUAL_IDENTIFIER_EXPANSION='\uE235'
typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_PYENV_SHOW_SYSTEM=false
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND='#f9e2af'
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false

typeset -g POWERLEVEL9K_GOENV_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_GOENV_FOREGROUND='#89b4fa'
typeset -g POWERLEVEL9K_GOENV_VISUAL_IDENTIFIER_EXPANSION='\uE626'
typeset -g POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_GOENV_SHOW_SYSTEM=false

typeset -g POWERLEVEL9K_NVM_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_NVM_FOREGROUND='#a6e3a1'
typeset -g POWERLEVEL9K_NVM_VISUAL_IDENTIFIER_EXPANSION='\uE718'
typeset -g POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_NVM_SHOW_SYSTEM=false

typeset -g POWERLEVEL9K_RBENV_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_RBENV_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_RBENV_VISUAL_IDENTIFIER_EXPANSION='\uE791'
typeset -g POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_RBENV_SHOW_SYSTEM=false

typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND='#f38ba8'
typeset -g POWERLEVEL9K_JAVA_VERSION_VISUAL_IDENTIFIER_EXPANSION='\uE738'
typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false

typeset -g POWERLEVEL9K_TIME_BACKGROUND='#313244'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#cdd6f4'
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
